import { string } from "yup/lib/locale"

declare namespace NodeJS {
	interface ProcessEnv {
		NEXTAUTH_URL: string
		NEXT_PUBLIC_BASEURL: string
		NEXT_PUBLIC_API_PATH: string
		NEXT_PUBLIC_MISCELLANEOUS_PATH: string
		NEXT_PUBLIC_UPLOAD_URL: string
		NEXT_PUBLIC_DEVELOPER_PATH: string
		NEXT_PUBLIC_USER_PATH: string
		NEXT_PUBLIC_TRANSACTION_PATH: string
		NEXT_PUBLIC_PROJECT_CATEGORY_CODE: string
		NEXT_PUBLIC_PROJECT_LEGAL_DOCUMENT_CODE: string
		NEXT_PUBLIC_PROJECT_SUPPORT_DOCUMENT_CODE: string
		NEXT_PUBLIC_TYPE_UNIT_SUPPORT_DOCUMENT_CODE: string
		NEXT_PUBLIC_AUTH_URL:string
		NEXT_PUBLIC_UNIT_CATEGORY_CODE:string
		NEXT_PUBLIC_UNIT_CERTIFICATE_CODE:string
		NEXT_PUBLIC_UNIT_PREVILEGE_CODE:string
		NEXT_PUBLIC_UNIT_FACILITY_CODE:string
		NEXT_PUBLIC_UNIT_EXTRA_CODE:string
		NEXT_PUBLIC_UNIT_FREE_CODE:string
		NEXT_PUBLIC_UNIT_STATUS_CODE:string
		NEXT_PUBLIC_UNIT_STATUS_TRANSACTION_CODE:string
		NEXT_PUBLIC_TRANSACTION_SCHEDULE_DOCUMENT_CODE:string
		NEXT_PUBLIC_TRANSACTION_BUYER_DOCUMENT_CODE:string
		NEXT_PUBLIC_ONESIGNAL_APPID:string
		NEXT_PUBLIC_URL_CHAT:string
		NEXT_PUBLIC_MQQT_BROKER: string
		NEXT_PUBLIC_MQQT_USERNAME: string
		NEXT_PUBLIC_MQQT_PASSWORD: string
		NEXT_PUBLIC_INBOX_PATH: string
	}
}
